name: HTML Check

on: [pull_request]

jobs:
  check-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Clone Repo
        run: echo "HTML checked!"
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v6
      - name: Check HTML
        run: | 
          npm install -g htmlhint 
          htmlhint *.html